# Generated by Django 4.2.16 on 2024-11-24 21:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Hikayemiz')),
                ('detail', models.TextField(blank=True, max_length=450, verbose_name='Biz Kimiz?')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Adres')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Soru')),
                ('answer', models.TextField(blank=True, verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Sıkça Sorulan Sorular',
                'verbose_name_plural': 'Sıkça Sorulan Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Üye Fotoğrafı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='settings.about', verbose_name='Hakkımızda')),
            ],
            options={
                'verbose_name': 'Gönderim ve İade Politikası',
                'verbose_name_plural': 'Gönderim ve İade Politikaları',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ayarlar', max_length=100, verbose_name='Başlık')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=29.99, max_digits=10, verbose_name='Kargo Ücreti')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Ücretsiz Kargo Limiti')),
                ('shipping_returns', tinymce.models.HTMLField(blank=True, verbose_name='Gönderim ve İade Politikası')),
                ('shop_policy', tinymce.models.HTMLField(blank=True, verbose_name='Mağaza Politikası')),
                ('aboutus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings.about', verbose_name='Hakkımızda ve Ekip Üyeleri')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings.contactinfo', verbose_name='İletişim Bilgileri')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings.faq', verbose_name='Sıkça Sorulan Sorular')),
            ],
            options={
                'verbose_name': 'Ayarlar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
    ]
