# Generated by Django 4.2.16 on 2024-12-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'Ekip Üyesi', 'verbose_name_plural': 'Ekip Üyeleri'},
        ),
    ]
