# Generated by Django 4.2.16 on 2024-11-24 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10, verbose_name='Stok Durumu')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('detail', models.TextField(blank=True, max_length=450, verbose_name='Ürün Bilgisi Detayı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('amount', models.IntegerField(default=0, verbose_name='Miktar')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='False', max_length=10, verbose_name='Stok Durumu')),
                ('roast', models.CharField(choices=[('Light', 'Hafif Kavrulmuş'), ('Medium', 'Orta Kavrulmuş'), ('Dark', 'Koyu Kavrulmuş ')], default='Light', max_length=50, verbose_name='Kavurma Seviyesi')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='En Çok Satan')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='İndirimde')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='İndirimli Fiyat')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promosyon Kodu')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='İndirim Oranı')),
                ('valid_from', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('valid_to', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiflik Durumu')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/images/', verbose_name='Resim')),
                ('video', models.FileField(blank=True, help_text='MP4, WebM formatları desteklenir', null=True, upload_to='workshops/videos/', verbose_name='Video')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Atölye',
                'verbose_name_plural': 'Atölyeler',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='Ürün Görseli')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['order'],
            },
        ),
    ]
