# Generated by Django 4.2.16 on 2024-11-24 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipname', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('shipphone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('shipemail', models.CharField(max_length=20, verbose_name='Email')),
                ('shipaddress', models.CharField(max_length=150, verbose_name='Adres')),
                ('total', models.FloatField(verbose_name='Toplam')),
                ('status', models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Onaylandı'), ('Preaparing', 'Hazırlanıyor'), ('OnShipping', 'Kargoya Verildi'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10, verbose_name='Durum')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Not')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
