# Generated by Django 4.2.16 on 2024-12-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
